### ISSUE TITLE
more info

### ISSUE THREAD

**Issue by cocodrino** [Beetrack/aws-ses-sns-dasboard#2]
Hello!..Good day!!...I wish to have more info about this code, can you upload an image with the dashboard and the alerts?...how configure this for SES, where must I put my credentials?...I just download the project and run it, seems than it's running in the background but localhost:8000/ shows a 404 page not found...also the route /dashboard

hope you can give me more details about this code and how use it...thank you!!

**Comment by kalelc** [comment]
Hello, this project is a mini dashboard to Amazon SES. Basically it is an app with golang that define endpoints to save a copy the email generate from Amazon SES in Amazon S3 and get all notifications (included filters).

Remember to initialize the project to set up Amazon SNS with app to allow get request from Amazon SNS to your application ([http://docs.aws.amazon.com/sns/latest/dg/SubscribeTopic.html](http://docs.aws.amazon.com/sns/latest/dg/SubscribeTopic.html)).
